import type { TrailMap } from "./scan.js";

export function formatText(map: TrailMap): string {
  const lines: string[] = [];
  lines.push(`Trail: ${map.root}`);
  lines.push("─".repeat(56));
  lines.push("");

  if (map.name) lines.push(`Package: ${map.name}`);
  if (map.description) lines.push(`About:   ${map.description}`);
  if (map.readmeIntro) lines.push(`\nREADME\n${map.readmeIntro}`);
  lines.push("");

  lines.push("DIRECTORIES");
  if (map.directories.length === 0) {
    lines.push("  (none at top level)");
  } else {
    for (const d of map.directories) {
      lines.push(`  · ${d.name}/ — ${d.hint}`);
    }
  }
  lines.push("");

  if (Object.keys(map.scripts).length > 0) {
    lines.push("SCRIPTS");
    for (const [name, cmd] of Object.entries(map.scripts)) {
      lines.push(`  ${name.padEnd(12)} ${cmd}`);
    }
    lines.push("");
  }

  lines.push("START HERE");
  for (const step of map.startHere) {
    lines.push(`  → ${step}`);
  }
  lines.push("");
  lines.push("— trail · leave a thread, find your way");

  return lines.join("\n");
}

export function formatMarkdown(map: TrailMap): string {
  const lines: string[] = [];
  lines.push(`# Trail: ${map.root}`);
  lines.push("");
  if (map.name) lines.push(`**Package:** \`${map.name}\``);
  if (map.description) lines.push(`\n${map.description}`);
  if (map.readmeIntro) {
    lines.push("\n## From the README\n");
    lines.push(map.readmeIntro);
  }
  lines.push("\n## Directory map\n");
  if (map.directories.length === 0) {
    lines.push("_No top-level directories._");
  } else {
    lines.push("| Path | Likely role |");
    lines.push("|------|-------------|");
    for (const d of map.directories) {
      lines.push(`| \`${d.name}/\` | ${d.hint} |`);
    }
  }
  if (Object.keys(map.scripts).length > 0) {
    lines.push("\n## Scripts\n");
    lines.push("| Script | Command |");
    lines.push("|--------|---------|");
    for (const [name, cmd] of Object.entries(map.scripts)) {
      lines.push(`| \`${name}\` | \`${cmd}\` |`);
    }
  }
  lines.push("\n## Start here\n");
  for (const step of map.startHere) {
    lines.push(`- ${step}`);
  }
  lines.push("\n---\n*Generated by [trail](https://github.com/Ariadne-Dev/trail)*");
  return lines.join("\n");
}

export function formatJson(map: TrailMap): string {
  return JSON.stringify(map, null, 2);
}
